model:
  type: stream-llm
  path: ./models/Meta-Llama-3-8B-Instruct
  n_init: 128
  n_local: 1024
  fattn: false
  base: 500000
  distance_scale: 1.0

max_len: 2147483647
chunk_size: 8192
conv_type: llama-3-inst